// LeadSignal — production deployment pipeline.
//
// Design notes (this differs from the older TracifyHR pipeline on purpose):
//
//  · Images are the deploy unit, not directories. Jenkins builds and tags
//    leadsignal-api:build-N / leadsignal-frontend:build-N; the compose file
//    only runs a tag. Rollback is therefore "re-run the previous tag" — a few
//    seconds — instead of rebuilding a commit that may no longer be checked out.
//  · The compose file is committed (docker-compose.prod.yml), not generated by
//    a heredoc inside this file. It is reviewable, diffable and testable.
//  · No --no-cache by default. The Dockerfiles copy manifests before source, so
//    a code-only change reuses the install layer. Use FORCE_REBUILD after a
//    base-image or system-dependency change.
//  · Postgres and Redis are NOT recreated on a deploy. Only api/worker/frontend
//    are swapped, so a routine deploy never risks the data services.
//  · No sudo anywhere. /var/www/leadsignal and /opt/leadsignal/env are owned by
//    the jenkins user (see deploy/scripts/bootstrap-server.sh), which removes an
//    entire class of "permission denied halfway through a deploy" failures.

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'RUN_TESTS',
            defaultValue: true,
            description: 'Run the backend unit suite before building images.')
        booleanParam(
            name: 'FORCE_REBUILD',
            defaultValue: false,
            description: 'Build images with --no-cache. Needed after a base-image or apt-dependency change.')
        booleanParam(
            name: 'RECREATE_DATA_SERVICES',
            defaultValue: false,
            description: 'Also recreate the Postgres/Redis containers. Off by default — data services stay up across deploys.')
        string(
            name: 'ROLLBACK_TO',
            defaultValue: '',
            description: 'Emergency use only: an existing image tag (e.g. build-41). Skips build/tests and re-deploys that tag.')
    }

    options {
        // Global watchdog — any hang (network stall, wedged docker daemon) is
        // killed here rather than sitting "still running" forever.
        timeout(time: 40, unit: 'MINUTES')
        // One deploy at a time. Stacked deploys against a shared compose project
        // corrupt the last-good-tag marker the rollback path depends on.
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '20'))
        timestamps()
        // A failing parallel branch should stop its sibling immediately instead
        // of burning another five minutes on a build we are going to discard.
        parallelsAlwaysFailFast()
    }

    environment {
        // ── Filesystem layout ────────────────────────────────────────────────
        // Everything lives under one jenkins-owned root, so promote/rollback are
        // plain mv/rm with no privilege escalation.
        APP_ROOT    = '/var/www/leadsignal'
        DEPLOY_DIR  = '/var/www/leadsignal/current'
        STAGING_DIR = '/var/www/leadsignal/staging'
        PREV_DIR    = '/var/www/leadsignal/prev'

        // Persistent, never-deployed secrets. Survives every promote/rollback.
        ENV_STORE      = '/opt/leadsignal/env'
        SERVER_DEPLOY_ENV  = '/opt/leadsignal/env/deploy.env'   // POSTGRES_* credentials
        SERVER_BACKEND_ENV = '/opt/leadsignal/env/backend.env'  // app secrets (API keys, SMTP)
        LAST_GOOD_TAG_FILE = '/opt/leadsignal/env/.last-good-tag'

        // ── Compose / images ─────────────────────────────────────────────────
        COMPOSE_PROJECT_NAME = 'leadsignal-prod'
        COMPOSE_FILE_NAME    = 'docker-compose.prod.yml'
        API_IMAGE  = 'leadsignal-api'
        WEB_IMAGE  = 'leadsignal-frontend'
        IMAGE_TAG  = "build-${BUILD_NUMBER}"
        // Keep this many tagged builds around for rollback; prune the rest.
        KEEP_IMAGE_TAGS = '4'

        DOCKER_BUILDKIT          = '1'
        COMPOSE_DOCKER_CLI_BUILD = '1'

        // ── Host ports ───────────────────────────────────────────────────────
        // All bound to 127.0.0.1 by the compose file; nginx is the only public
        // door. Chosen to avoid TracifyHR (6660, 6967) and Jenkins (8080).
        API_HOST_PORT      = '6690'
        WORKER_HOST_PORT   = '6691'
        WEB_HOST_PORT      = '6890'
        POSTGRES_HOST_PORT = '5436'
        REDIS_HOST_PORT    = '6390'

        // ── Public identity ──────────────────────────────────────────────────
        APP_URL           = 'https://leadgen.deventiatech.com'
        API_URL           = 'https://leadgenapi.deventiatech.com'
        ALLOWED_ORIGINS   = 'https://leadgen.deventiatech.com,https://leadgenapi.deventiatech.com'
        CRAWLER_CONTACT_URL = 'https://leadgen.deventiatech.com/bot'
        CRAWLER_USER_AGENT  = 'LeadSignalBot/1.0 (+https://leadgen.deventiatech.com/bot; contact: bot@deventiatech.com)'
    }

    stages {

        stage('Checkout') {
            when { expression { return !params.ROLLBACK_TO?.trim() } }
            steps {
                checkout scmGit(
                    branches: [[name: '*/prod']],
                    extensions: [[$class: 'CloneOption', shallow: true, depth: 1, noTags: true]],
                    userRemoteConfigs: [[
                        credentialsId: 'abdulmajid-git-credentials',
                        url: 'https://github.com/AbdulMajid1m1/lead-gen.git'
                    ]]
                )
                script {
                    env.GIT_SHA = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    currentBuild.description = "${env.IMAGE_TAG} · ${env.GIT_SHA}"
                }
            }
        }

        // Everything that can invalidate a deploy is checked here, before a
        // single file is copied or a single container is touched. A failure in
        // this stage leaves production completely untouched.
        stage('Preflight') {
            steps {
                script {
                    if (params.ROLLBACK_TO?.trim()) {
                        env.IMAGE_TAG = params.ROLLBACK_TO.trim()
                        currentBuild.description = "ROLLBACK → ${env.IMAGE_TAG}"
                        echo "⏪ Rollback mode: redeploying ${env.IMAGE_TAG}, skipping checkout/tests/build."
                    }
                }
                sh '''
                    set -eu
                    fail=0

                    command -v docker >/dev/null || { echo "❌ docker not on PATH"; fail=1; }
                    docker compose version >/dev/null 2>&1 || { echo "❌ docker compose v2 plugin missing"; fail=1; }
                    docker info >/dev/null 2>&1 || { echo "❌ cannot talk to the docker daemon (is jenkins in the docker group?)"; fail=1; }

                    for d in "$APP_ROOT" "$ENV_STORE"; do
                        [ -d "$d" ] || { echo "❌ $d is missing — run deploy/scripts/bootstrap-server.sh"; fail=1; continue; }
                        [ -w "$d" ] || { echo "❌ $d is not writable by $(whoami) — run bootstrap-server.sh"; fail=1; }
                    done

                    for f in "$SERVER_DEPLOY_ENV" "$SERVER_BACKEND_ENV"; do
                        [ -f "$f" ] || { echo "❌ required env file missing: $f"; fail=1; }
                    done

                    # A missing credential surfaces here as one clear line rather
                    # than as a Postgres container that refuses to initialise.
                    if [ -f "$SERVER_DEPLOY_ENV" ]; then
                        for key in POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB; do
                            grep -qE "^${key}=.+" "$SERVER_DEPLOY_ENV" || { echo "❌ $key is missing or empty in $SERVER_DEPLOY_ENV"; fail=1; }
                        done
                    fi

                    # The API hard-refuses to boot in production without a console
                    # account (configs/envConfig.js). Without this check the only
                    # symptom is a container that restarts forever and a deploy
                    # that fails at --wait with nothing pointing at the cause.
                    if [ -f "$SERVER_BACKEND_ENV" ]; then
                        for key in ADMIN_EMAIL ADMIN_PASSWORD; do
                            grep -qE "^${key}=.+" "$SERVER_BACKEND_ENV" \\
                                || { echo "❌ $key is missing or empty in $SERVER_BACKEND_ENV — the API will not start without it"; fail=1; }
                        done
                    fi

                    # Free disk is the single most common cause of a half-finished
                    # image build, and it fails in a very unhelpful way.
                    avail_mb=$(df -Pm /var/lib/docker 2>/dev/null | awk 'NR==2 {print $4}')
                    [ -n "$avail_mb" ] || avail_mb=99999
                    if [ "$avail_mb" -lt 3000 ]; then
                        echo "❌ only ${avail_mb}MB free on the docker filesystem; need ~3GB. Run: docker system prune -af"
                        fail=1
                    fi

                    [ "$fail" -eq 0 ] || { echo "Preflight failed — production untouched."; exit 1; }
                    echo "✅ Preflight passed."
                '''
                script {
                    // Recorded before anything changes so the failure handler
                    // always knows what to fall back to.
                    env.PREV_TAG = sh(
                        script: "cat ${env.LAST_GOOD_TAG_FILE} 2>/dev/null || true",
                        returnStdout: true).trim()
                    echo env.PREV_TAG ? "Last known-good tag: ${env.PREV_TAG}" : "No previous deploy recorded (first run)."
                }
            }
        }

        stage('Verify & Build') {
            when { expression { return !params.ROLLBACK_TO?.trim() } }
            parallel {

                // The unit suite is dependency-free (no database, no Redis),
                // so it runs in a throwaway node container rather than against
                // whatever Node version happens to be on the Jenkins host. The
                // npm cache lives in a named volume, so repeat installs are
                // fast, and it runs alongside the image builds — near-zero
                // added wall-clock.
                stage('Backend tests') {
                    when { expression { return params.RUN_TESTS } }
                    steps {
                        // The source is mounted read-only and copied inside the
                        // container, so npm never writes a root-owned
                        // node_modules into the Jenkins workspace — the classic
                        // way this pattern breaks cleanWs on the next build.
                        retry(2) {
                            sh '''
                                set -eu
                                docker run --rm \\
                                    -v "$WORKSPACE/backend":/src:ro \\
                                    -v leadsignal_npm_cache:/root/.npm \\
                                    -w /app \\
                                    node:22-slim \\
                                    sh -ec "cp -a /src/. /app/ && npm ci --no-audit --no-fund && npx vitest run --reporter=dot"
                            '''
                        }
                    }
                }

                stage('Build API image') {
                    steps {
                        script {
                            def cacheFlag = params.FORCE_REBUILD ? '--no-cache' : ''
                            retry(2) {
                                sh """
                                    set -eu
                                    docker build ${cacheFlag} \\
                                        --pull \\
                                        --label "org.opencontainers.image.revision=\${GIT_SHA:-unknown}" \\
                                        --label "com.leadsignal.build=${BUILD_NUMBER}" \\
                                        -t ${API_IMAGE}:${IMAGE_TAG} \\
                                        ./backend
                                """
                            }
                        }
                    }
                }

                stage('Build frontend image') {
                    steps {
                        script {
                            def cacheFlag = params.FORCE_REBUILD ? '--no-cache' : ''
                            retry(2) {
                                sh """
                                    set -eu
                                    docker build ${cacheFlag} \\
                                        --pull \\
                                        --label "org.opencontainers.image.revision=\${GIT_SHA:-unknown}" \\
                                        --label "com.leadsignal.build=${BUILD_NUMBER}" \\
                                        -t ${WEB_IMAGE}:${IMAGE_TAG} \\
                                        ./frontend
                                """
                            }
                        }
                    }
                }
            }
        }

        // Assemble the exact directory production will run from, off to the
        // side. Nothing live is touched until 'Promote'.
        stage('Stage release') {
            steps {
                sh '''
                    set -eu
                    rm -rf "$STAGING_DIR"
                    mkdir -p "$STAGING_DIR"

                    if [ -n "${ROLLBACK_TO:-}" ]; then
                        # Rollback reuses the currently-live release directory —
                        # the compose file that shipped with it is the one that
                        # matches the image we are rolling back to.
                        cp -a "$DEPLOY_DIR/." "$STAGING_DIR/"
                    else
                        cp "$COMPOSE_FILE_NAME" "$STAGING_DIR/"
                        mkdir -p "$STAGING_DIR/deploy"
                        cp -a deploy/. "$STAGING_DIR/deploy/" 2>/dev/null || true
                    fi

                    # Application secrets — copied in, never committed.
                    install -m 600 "$SERVER_BACKEND_ENV" "$STAGING_DIR/backend.env"

                    # Compose interpolation file: credentials from the server
                    # store, everything else pinned by the Jenkinsfile so a port
                    # or origin change is a reviewable commit, not an ssh session.
                    {
                        echo "# Generated by Jenkins build ${BUILD_NUMBER} — do not edit by hand."
                        grep -E '^(POSTGRES_USER|POSTGRES_PASSWORD|POSTGRES_DB)=' "$SERVER_DEPLOY_ENV"
                        echo "IMAGE_TAG=$IMAGE_TAG"
                        echo "API_IMAGE=$API_IMAGE"
                        echo "WEB_IMAGE=$WEB_IMAGE"
                        echo "API_HOST_PORT=$API_HOST_PORT"
                        echo "WORKER_HOST_PORT=$WORKER_HOST_PORT"
                        echo "WEB_HOST_PORT=$WEB_HOST_PORT"
                        echo "POSTGRES_HOST_PORT=$POSTGRES_HOST_PORT"
                        echo "REDIS_HOST_PORT=$REDIS_HOST_PORT"
                        echo "APP_URL=$APP_URL"
                        echo "ALLOWED_ORIGINS=$ALLOWED_ORIGINS"
                        echo "CRAWLER_USER_AGENT=$CRAWLER_USER_AGENT"
                        echo "CRAWLER_CONTACT_URL=$CRAWLER_CONTACT_URL"
                    } > "$STAGING_DIR/.env"
                    chmod 600 "$STAGING_DIR/.env"

                    # Catch a broken compose file / missing variable now, while
                    # the live stack is still the old one.
                    cd "$STAGING_DIR"
                    docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" config -q
                    echo "✅ Release staged and compose config validated."
                '''
            }
        }

        // Postgres and Redis are deliberately started from the *staging* copy
        // and left alone from here on. They are stateful and shared across
        // releases; a code deploy has no business restarting them.
        stage('Data services') {
            steps {
                sh '''
                    set -eu
                    cd "$STAGING_DIR"
                    if [ "${RECREATE_DATA_SERVICES:-false}" = "true" ]; then
                        echo "⚠️  RECREATE_DATA_SERVICES=true — forcing Postgres/Redis recreation."
                        docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                            up -d --force-recreate --wait postgres redis
                    else
                        docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                            up -d --wait postgres redis
                    fi
                    echo "✅ Postgres and Redis healthy."
                '''
            }
        }

        stage('Database migrations') {
            when { expression { return !params.ROLLBACK_TO?.trim() } }
            steps {
                // Prisma *migrations* (not `db push`): every schema change is a
                // reviewed SQL file in prisma/schema/migrations, so the deploy
                // applies a known diff rather than inferring one. There is no
                // --accept-data-loss escape hatch here and there should not be —
                // a destructive migration must be an explicit, reviewed commit.
                //
                // Migrations are NOT rolled back automatically. That is why the
                // schema policy is additive-only: a new release must be able to
                // run against the previous schema and vice versa.
                sh '''
                    set -eu
                    cd "$STAGING_DIR"

                    echo "── Pending migrations ─────────────────────────────"
                    docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                        run --rm --no-deps api npx prisma migrate status --schema=prisma/schema || true
                    echo "───────────────────────────────────────────────────"

                    docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                        run --rm --no-deps api npx prisma migrate deploy --schema=prisma/schema

                    echo "✅ Schema up to date."
                '''
            }
        }

        stage('Promote') {
            steps {
                sh '''
                    set -eu
                    rm -rf "$PREV_DIR"
                    [ -d "$DEPLOY_DIR" ] && mv "$DEPLOY_DIR" "$PREV_DIR" || true
                    mv "$STAGING_DIR" "$DEPLOY_DIR"

                    # In-flight marker. Cleared only by post.success, so *any*
                    # later failure — including a failed smoke test — is seen by
                    # the failure handler as "roll me back".
                    touch "$DEPLOY_DIR/.deploy-incomplete"
                    echo "✅ Promoted release to $DEPLOY_DIR"
                '''
            }
        }

        stage('Deploy services') {
            steps {
                sh '''
                    set -eu
                    cd "$DEPLOY_DIR"
                    # --wait blocks until every started service reports healthy,
                    # so a container that boots and immediately dies fails the
                    # build here rather than 404ing for users an hour later.
                    docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                        up -d --wait --remove-orphans api worker frontend
                    echo "✅ api / worker / frontend are up and healthy."
                '''
            }
        }

        // --wait only proves the containers' own healthchecks pass. This proves
        // the actual request paths users hit are wired correctly.
        stage('Smoke test') {
            steps {
                sh '''
                    set -eu

                    check() {
                        name="$1"; url="$2"
                        for i in 1 2 3 4 5 6 7 8 9 10; do
                            if curl -fsS --max-time 10 "$url" >/dev/null 2>&1; then
                                echo "  ✅ $name"
                                return 0
                            fi
                            sleep 3
                        done
                        echo "  ❌ $name — $url never answered"
                        return 1
                    }

                    check "API health          " "http://127.0.0.1:${API_HOST_PORT}/api/health"
                    check "Worker health       " "http://127.0.0.1:${WORKER_HOST_PORT}/health"
                    check "Frontend index      " "http://127.0.0.1:${WEB_HOST_PORT}/"
                    # Proves the SPA container's internal /api → api:4100 proxy
                    # works. Broken proxying is invisible to every other check
                    # and breaks every page in the app.
                    check "Frontend → API proxy" "http://127.0.0.1:${WEB_HOST_PORT}/api/health"

                    echo "✅ Smoke tests passed."
                '''
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                    set -eu

                    # Keep the newest N build tags per image so ROLLBACK_TO has
                    # something to aim at; drop the rest.
                    #
                    # Ordered by build number numerically, not by tag string and
                    # not by image timestamp. A string sort puts build-9 above
                    # build-12; a timestamp sort is right in practice but ties at
                    # one-second granularity and then falls back to that same bad
                    # string sort. The build number is what we actually mean.
                    prune_image() {
                        repo="$1"
                        docker images "$repo" --filter "reference=$repo:build-*" --format '{{.Tag}}' \
                            | grep -E '^build-[0-9]+$' \
                            | sed 's/^build-//' \
                            | sort -rn \
                            | tail -n +$((KEEP_IMAGE_TAGS + 1)) \
                            | while read -r num; do
                                  echo "  removing $repo:build-$num"
                                  docker rmi "$repo:build-$num" >/dev/null 2>&1 || true
                              done
                    }
                    prune_image "$API_IMAGE"
                    prune_image "$WEB_IMAGE"

                    docker image prune -f >/dev/null
                    rm -rf "$PREV_DIR"
                    echo "✅ Cleanup done (kept newest $KEEP_IMAGE_TAGS tags per image)."
                '''
            }
        }
    }

    post {
        success {
            sh '''
                set -eu
                rm -f "$DEPLOY_DIR/.deploy-incomplete"
                # Only recorded once the release has actually served traffic —
                # this is what a future rollback aims at.
                printf '%s' "$IMAGE_TAG" > "$LAST_GOOD_TAG_FILE"
            '''
            echo "🚀 LeadSignal ${env.IMAGE_TAG} is live — ${env.APP_URL} / ${env.API_URL}"
        }

        failure {
            // Every command is guarded and every docker call is bounded by
            // `timeout`. A wedged daemon must not turn a failed deploy into a
            // build that hangs forever.
            sh '''
                set +e
                echo "❌ Deploy failed."

                if [ -f "$DEPLOY_DIR/.deploy-incomplete" ] && [ -n "${PREV_TAG:-}" ]; then
                    echo "🔄 Rolling back to $PREV_TAG ..."

                    # Restore the release directory that matches the old image.
                    if [ -d "$PREV_DIR" ]; then
                        rm -rf "$DEPLOY_DIR"
                        mv "$PREV_DIR" "$DEPLOY_DIR"
                    fi

                    cd "$DEPLOY_DIR" || exit 0
                    # Point compose back at the previous tag. Editing the single
                    # IMAGE_TAG line is enough — the images are still on disk.
                    sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$PREV_TAG/" .env

                    timeout 240 docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                        up -d --wait --remove-orphans api worker frontend

                    if curl -fsS --max-time 10 "http://127.0.0.1:${API_HOST_PORT}/api/health" >/dev/null 2>&1; then
                        echo "✅ Rollback complete — $PREV_TAG is serving again."
                        rm -f "$DEPLOY_DIR/.deploy-incomplete"
                    else
                        echo "🚨 ROLLBACK DID NOT RECOVER THE API. Manual intervention required."
                        echo "   cd $DEPLOY_DIR && docker compose -f $COMPOSE_FILE_NAME -p $COMPOSE_PROJECT_NAME logs --tail=200"
                    fi
                else
                    echo "Failed before promote (or no previous release) — live stack untouched."
                fi

                rm -rf "$STAGING_DIR"

                echo "── Container logs (last 60 lines) ─────────────────"
                timeout 45 docker compose -p "$COMPOSE_PROJECT_NAME" logs --tail=60 --no-color 2>&1 \
                    || echo "(no logs available — compose project may be empty or wedged)"
                echo "───────────────────────────────────────────────────"
            '''
        }

        aborted {
            sh '''
                set +e
                echo "⚠️  Build aborted — cleaning up."
                if [ -f "$DEPLOY_DIR/.deploy-incomplete" ] && [ -n "${PREV_TAG:-}" ] && [ -d "$PREV_DIR" ]; then
                    rm -rf "$DEPLOY_DIR"
                    mv "$PREV_DIR" "$DEPLOY_DIR"
                    cd "$DEPLOY_DIR" && sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$PREV_TAG/" .env
                    timeout 240 docker compose -f "$COMPOSE_FILE_NAME" --env-file .env -p "$COMPOSE_PROJECT_NAME" \
                        up -d --wait api worker frontend
                fi
                rm -rf "$STAGING_DIR"
            '''
        }

        always {
            // The workspace holds a full node_modules from the test stage.
            // Left alone it grows without bound across builds.
            // The clone is shallow (depth 1) and nothing installs into the
            // workspace, so a full wipe costs a few seconds and guarantees the
            // next build sees exactly what is on the branch.
            cleanWs(deleteDirs: true, notFailBuild: true)
        }
    }
}
