import { emailBelongsToPlatform } from "../verify/hostedPlatforms.js";

/**
 * Tell a machine's answer from a person's.
 *
 * A reply is the one inbound event that hands a lead to a human and ends its
 * follow-up sequence, so it has to be a person. Two kinds of message were
 * getting through as replies:
 *
 *   - Ticket acknowledgements. Menufy's help desk answered a cold email with
 *     "Your request (8115635) has been received and is being reviewed by our
 *     Support Team" — carrying our Message-ID in In-Reply-To, so it matched
 *     the thread exactly as a real answer would, marked the lead REPLIED and
 *     put it in the "someone wrote back" queue.
 *   - Out-of-office and receipt confirmations. Carambar, Berlin: "Mit dieser
 *     Antwort bestätigen wir den Eingang Ihrer E-Mail … keine persönliche
 *     Antwort, sondern um eine automatisierte Email".
 *
 * Pure, so the real cases live in the test file. Evidence is weighed rather
 * than any single phrase trusted: a header that declares the message
 * automatic is decisive on its own; body phrases need two, or one plus a
 * ticket number, because a person can write "I have received your email" too.
 *
 * The cost of the two mistakes is not symmetrical. Calling a person a robot
 * leaves a live reply unread in the thread (it is still stored, just not
 * promoted) — recoverable. Calling a robot a person silently cancels every
 * follow-up and misreports the reply rate. So the bar is set for the former.
 */

/** RFC 3834 and the vendor headers that mean the same thing. Decisive. */
const AUTO_HEADER_RES = [
  /^auto-submitted:\s*(?:auto-replied|auto-generated|auto-notified)/im,
  /^precedence:\s*(?:bulk|auto_reply|junk|list)\b/im,
  /^x-auto-?respond(?:er)?:/im,
  /^x-autoreply(?:-from)?:/im,
  /^x-auto-response-suppress:/im,
  /^x-autogenerated:\s*(?:reply|auto)/im,
  /^x-(?:zendesk|freshdesk|helpscout|intercom|kayako|hubspot|front|gorgias|zohodesk)-/im,
  /^x-mailer:\s*(?:zendesk|freshdesk|help ?scout|intercom|kayako|zoho ?desk)/im,
];

/** Subjects that only ever come from a system. Decisive. */
const AUTO_SUBJECT_RES = [
  /^\s*(?:re:\s*)?(?:auto(?:matic|mated)?[\s-]*(?:reply|response|antwort)|automatische antwort|réponse automatique|risposta automatica|respuesta automática|resposta automática|abwesenheit(?:snotiz)?|out[\s-]*of[\s-]*(?:the[\s-]*)?office|ooo\b|away from (?:the |my )?(?:office|desk|email)|on (?:annual |maternity |paternity |sick )?leave)/i,
  /^\s*(?:re:\s*)?\[(?:request|ticket|case|support) (?:received|created|opened|#?\d+)\]/i,
  /^\s*(?:re:\s*)?(?:request|ticket|case|support request|your (?:request|enquiry|inquiry|message|email))\s+(?:received|has been received|created|opened|#\s*\d+)/i,
  /^\s*(?:re:\s*)?(?:we(?:'ve| have) received your (?:request|message|email|enquiry|inquiry)|thank you for contacting)/i,
  /\[#?\s*\d{4,}\]|\(?ticket\s*#?\s*\d{3,}\)?|case\s*(?:id|number|#)\s*:?\s*\d{3,}/i,
];

/** Body phrases that describe a system talking. Two needed, or one plus a ticket id. */
const AUTO_BODY_RES = [
  /please (?:type|write|enter) your reply above this line/i,
  /(?:your|the) (?:request|ticket|case|message|email|enquiry|inquiry|query) \(?#?\s*\d*\)? ?(?:has been|was|is) (?:received|logged|created|registered|opened|recorded)/i,
  /(?:has been|was) received and is being reviewed/i,
  /a new (?:request|ticket|case) \(?#?\d*\)? has been (?:created|opened|logged)/i,
  /this (?:is|was) an automat(?:ed|ic) (?:message|reply|response|email|e-mail|notification|acknowledg(?:e)?ment)/i,
  /(?:do not|don't|please do not) reply (?:directly )?to this (?:email|e-mail|message|address)/i,
  /(?:this|it) is (?:an? )?(?:auto(?:matic|mated)|system[- ]generated) (?:reply|response|message|e-?mail)/i,
  /(?:we|our (?:team|support team)) will (?:try (?:and|to) )?(?:get back|respond|reply|be in touch|contact you) (?:to you )?(?:as soon as|shortly|within|soon)/i,
  /(?:thank you|thanks) for (?:contacting|reaching out to|getting in touch with|your (?:email|message|enquiry|inquiry)) .{0,60}(?:support|help ?desk|customer (?:care|service|success))/i,
  /(?:i am|i'm|i will be) (?:currently )?(?:out of (?:the )?office|away from (?:the |my )?(?:office|desk)|on (?:annual |sick |maternity |paternity |parental )?leave|travel(?:l)?ing|on holiday|on vacation)/i,
  /(?:limited|no) access to (?:my )?e-?mail/i,
  /(?:will|shall) (?:respond|reply|get back to you|answer) (?:to your (?:email|message) )?(?:on|upon|when|after) (?:my|i) return/i,
  /(?:automatisierte|automatische) (?:e-?mail|antwort|nachricht)/i,
  /keine pers[öo]nliche antwort/i,
  /best[äa]tigen wir den eingang/i,
  /wir haben ihre (?:e-?mail|nachricht|anfrage) erhalten/i,
  /(?:bin|ist) (?:bis .{0,40} )?(?:nicht im (?:büro|haus)|abwesend|im urlaub)/i,
  /accus[ée] de r[ée]ception/i,
  /nous avons bien re[çc]u votre (?:message|demande|e-?mail)/i,
  /(?:hemos recibido|recebemos) (?:su|sua|tu) (?:mensaje|mensagem|solicitud|e-?mail|correo)/i,
  /abbiamo ricevuto la (?:sua|tua) (?:richiesta|email|e-mail)/i,
  /(?:تم استلام|لقد تلقينا) (?:طلبك|رسالتك|بريدك)/,
  /this email is a service from/i,
  /help ?(?:cent(?:er|re)|desk) (?:articles?|portal)/i,
];

const TICKET_ID_RE = /(?:request|ticket|case|reference|ref\.?|id)\s*(?:number|no\.?|#)?\s*[:#(]?\s*(\d{4,})/i;

const headerText = (headers) => {
  if (!headers) return "";
  if (typeof headers === "string") return headers;
  if (typeof headers === "object") {
    return Object.entries(headers).map(([k, v]) => `${k}: ${Array.isArray(v) ? v.join(", ") : v}`).join("\n");
  }
  return String(headers);
};

const clean = (s) => String(s || "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();

/**
 * @param {{from?:string, subject?:string, body?:string, headers?:string|object, recipientEmail?:string, companyDomain?:string}} input
 * @returns {{isAutoReply:boolean, kind:"TICKET_ACK"|"OUT_OF_OFFICE"|"AUTO_ACK"|null,
 *   platform:{domain:string,kind:string,label:string}|null, ticketId:string|null,
 *   reason:string|null, evidence:string[]}}
 */
export const classifyAutoReply = ({ from = "", subject = "", body = "", headers = "", companyDomain = null } = {}) => {
  const evidence = [];
  const head = headerText(headers);
  const subj = clean(subject);
  const text = clean(body).slice(0, 4000);

  let decisive = false;
  for (const re of AUTO_HEADER_RES) {
    const m = re.exec(head);
    if (m) { decisive = true; evidence.push(`header: ${m[0].trim().slice(0, 80)}`); break; }
  }
  for (const re of AUTO_SUBJECT_RES) {
    const m = re.exec(subj);
    if (m) { decisive = true; evidence.push(`subject: "${m[0].trim().slice(0, 80)}"`); break; }
  }

  let bodyHits = 0;
  for (const re of AUTO_BODY_RES) {
    const m = re.exec(text);
    if (!m) continue;
    bodyHits += 1;
    evidence.push(`body: "${m[0].slice(0, 80)}"`);
    if (bodyHits >= 3) break;
  }

  const ticketId = TICKET_ID_RE.exec(`${subj} ${text}`)?.[1] || null;
  const platform = emailBelongsToPlatform(from, companyDomain);

  const isAutoReply = decisive || bodyHits >= 2 || (bodyHits >= 1 && Boolean(ticketId));
  if (!isAutoReply) {
    return { isAutoReply: false, kind: null, platform, ticketId: null, reason: null, evidence };
  }

  // "Automatic reply:" is what Outlook and Gmail put on an out-of-office.
  const ooo = /out[\s-]*of[\s-]*(?:the[\s-]*)?office|abwesen|urlaub|on (?:annual |sick |maternity |paternity |parental )?leave|away from|vacation|holiday|return|auto(?:matic|mated)?[\s-]*reply|automatische antwort|réponse automatique|risposta automatica|respuesta automática/i;
  const ticket = /ticket|request|case|support|help ?desk|reviewed|above this line|service from/i;
  const kind = ticketId || ticket.test(`${subj} ${text}`) ? "TICKET_ACK"
    : ooo.test(`${subj} ${text}`) ? "OUT_OF_OFFICE"
    : "AUTO_ACK";

  const reason = kind === "TICKET_ACK"
    ? `A help-desk acknowledgement${ticketId ? ` (ticket ${ticketId})` : ""}${platform ? ` from ${platform.domain}` : ""}, not a person's answer.`
    : kind === "OUT_OF_OFFICE"
      ? "An out-of-office auto-responder, not a person's answer."
      : "An automatic receipt confirmation, not a person's answer.";

  return { isAutoReply: true, kind, platform, ticketId, reason, evidence };
};

export const __testables = { AUTO_HEADER_RES, AUTO_SUBJECT_RES, AUTO_BODY_RES };
