#!/usr/bin/env bash
#
# One-time server preparation for LeadSignal. Idempotent — safe to re-run.
#
#   sudo bash deploy/scripts/bootstrap-server.sh
#
# What it does and why:
#   · Creates /var/www/leadsignal and /opt/leadsignal/env owned by the jenkins
#     user. This is the reason the pipeline needs no sudo at all: promote and
#     rollback are plain mv/rm inside a directory jenkins owns, which removes
#     the whole class of "permission denied halfway through a deploy" failures.
#   · Seeds the two env files the pipeline requires, with a generated Postgres
#     password, so the first build cannot fail on a missing secret.
#   · Installs the nginx vhosts and the nightly database backup timer.
set -euo pipefail

DEPLOY_USER="${DEPLOY_USER:-jenkins}"
APP_ROOT="/var/www/leadsignal"
ENV_STORE="/opt/leadsignal/env"
BACKUP_DIR="/var/backups/leadsignal"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Set only when this run generates one, and echoed again in the closing summary.
ADMIN_PW_GENERATED=""

[[ $EUID -eq 0 ]] || { echo "Run me with sudo."; exit 1; }
id "$DEPLOY_USER" >/dev/null 2>&1 || { echo "User '$DEPLOY_USER' does not exist. Install Jenkins first, or set DEPLOY_USER."; exit 1; }

say() { printf '\n\033[1m▸ %s\033[0m\n' "$1"; }

say "Checking prerequisites"
missing=()
command -v docker  >/dev/null || missing+=("docker")
docker compose version >/dev/null 2>&1 || missing+=("docker-compose-plugin")
command -v nginx   >/dev/null || missing+=("nginx")
command -v certbot >/dev/null || missing+=("certbot")
if ((${#missing[@]})); then
    echo "Missing: ${missing[*]}"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo "  apt install -y nginx certbot python3-certbot-nginx"
    exit 1
fi

# Jenkins builds images and runs compose directly — it needs the docker socket.
if ! id -nG "$DEPLOY_USER" | grep -qw docker; then
    say "Adding $DEPLOY_USER to the docker group"
    usermod -aG docker "$DEPLOY_USER"
    echo "  ⚠️  Restart Jenkins for this to take effect: systemctl restart jenkins"
fi

say "Creating directories"
install -d -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 755 "$APP_ROOT"
install -d -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 700 /opt/leadsignal "$ENV_STORE"
install -d -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 750 "$BACKUP_DIR"
echo "  $APP_ROOT, $ENV_STORE, $BACKUP_DIR"

say "Seeding $ENV_STORE/deploy.env"
if [[ -f "$ENV_STORE/deploy.env" ]]; then
    echo "  already exists — left untouched"
else
    # Generated once and never rotated automatically: the Postgres volume is
    # initialised with this password and changing it later needs an ALTER ROLE,
    # not a file edit.
    pw="$(openssl rand -hex 24)"
    cat > "$ENV_STORE/deploy.env" <<EOF
# LeadSignal — infrastructure credentials. Never committed, never deployed.
# Generated by bootstrap-server.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
#
# POSTGRES_PASSWORD is baked into the Postgres data volume on first start.
# Changing it here later does NOT change the database — you must also run:
#   docker exec -it leadsignal_postgres_prod psql -U leadsignal -c "ALTER ROLE leadsignal PASSWORD 'new';"
POSTGRES_USER=leadsignal
POSTGRES_PASSWORD=$pw
POSTGRES_DB=leadsignal
EOF
    chown "$DEPLOY_USER:$DEPLOY_USER" "$ENV_STORE/deploy.env"
    chmod 600 "$ENV_STORE/deploy.env"
    echo "  created with a generated password"
fi

say "Seeding $ENV_STORE/backend.env"
if [[ -f "$ENV_STORE/backend.env" ]]; then
    echo "  already exists — left untouched"
elif [[ -f "$REPO_DIR/deploy/env/backend.env.prod.example" ]]; then
    install -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 600 \
        "$REPO_DIR/deploy/env/backend.env.prod.example" "$ENV_STORE/backend.env"

    # The API refuses to boot in production without a usable ADMIN_PASSWORD, so
    # generate one rather than leaving the template's blank and letting the
    # first deploy fail its healthcheck with a crash-looping container.
    admin_pw="$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)Aa1!"
    sed -i "s#^ADMIN_PASSWORD=.*#ADMIN_PASSWORD=$admin_pw#" "$ENV_STORE/backend.env"
    ADMIN_PW_GENERATED="$admin_pw"

    echo "  created from the template."
    echo "  ⚠️  A console password was generated. Save it now — it is not shown again:"
    echo ""
    echo "        password: $admin_pw"
    echo ""
    echo "  Set ADMIN_EMAIL and your API keys before the first deploy:"
    echo "     sudo -u $DEPLOY_USER nano $ENV_STORE/backend.env"
else
    install -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 600 /dev/null "$ENV_STORE/backend.env"
    echo "  created empty — populate it from deploy/env/backend.env.prod.example"
fi

say "Installing nginx configuration"
cp "$REPO_DIR/deploy/nginx/00-leadsignal-upgrade-map.conf" /etc/nginx/conf.d/
for site in leadgen-app leadgen-api; do
    cp "$REPO_DIR/deploy/nginx/$site.conf" "/etc/nginx/sites-available/$site"
    ln -sfn "/etc/nginx/sites-available/$site" "/etc/nginx/sites-enabled/$site"
    echo "  $site"
done
# The vhosts reference certificates that do not exist yet, so `nginx -t` will
# fail until certbot has run. That is expected on a first bootstrap.
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo "  nginx reloaded"
else
    echo "  ⚠️  nginx -t failed — almost certainly the missing TLS certs. Run:"
    echo "       certbot --nginx -d leadgen.deventiatech.com -d leadgenapi.deventiatech.com"
    echo "     then: nginx -t && systemctl reload nginx"
fi

say "Installing the nightly database backup timer"
install -m 755 "$REPO_DIR/deploy/scripts/backup-db.sh" /usr/local/bin/leadsignal-backup-db
cat > /etc/systemd/system/leadsignal-backup.service <<EOF
[Unit]
Description=LeadSignal nightly Postgres backup
After=docker.service

[Service]
Type=oneshot
User=$DEPLOY_USER
ExecStart=/usr/local/bin/leadsignal-backup-db
EOF
cat > /etc/systemd/system/leadsignal-backup.timer <<'EOF'
[Unit]
Description=Run the LeadSignal Postgres backup nightly

[Timer]
# 02:40 with jitter, so it does not collide with the worker's 02:15/03:30 jobs.
OnCalendar=*-*-* 02:40:00
RandomizedDelaySec=900
Persistent=true

[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now leadsignal-backup.timer
echo "  leadsignal-backup.timer enabled (nightly, 14-day retention)"

say "Firewall"
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
    echo "  ufw is active — the stack binds only to 127.0.0.1, so nothing to open beyond Nginx Full."
else
    echo "  ufw inactive. Recommended: ufw allow OpenSSH && ufw allow 'Nginx Full' && ufw enable"
fi

cat <<EOF

────────────────────────────────────────────────────────────────
✅ Bootstrap complete.

Next:
  1. Point DNS at this server:
        leadgen.deventiatech.com      A  <server-ip>
        leadgenapi.deventiatech.com   A  <server-ip>
  2. Issue certificates:
        certbot --nginx -d leadgen.deventiatech.com
        certbot --nginx -d leadgenapi.deventiatech.com
  3. Fill in secrets — ADMIN_EMAIL is required, the API will not boot without it:
        sudo -u $DEPLOY_USER nano $ENV_STORE/backend.env
${ADMIN_PW_GENERATED:+
     Console password generated for this box: $ADMIN_PW_GENERATED
     (change it after the first sign-in; the .env is only the initial value)}
  4. Create the Jenkins pipeline job (branch: prod, script: Jenkinsfile)
     and run it. The first build creates the database and applies migrations.
────────────────────────────────────────────────────────────────
EOF
